// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MongoDB.EntityFrameworkCore.FunctionalTests.Design;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CompiledModelTests.SimpleContext), typeof(SimpleContextModel))]
